"""added top_up field

Revision ID: 896e942bc87a
Revises: abfb62d1e907
Create Date: 2025-07-02 11:42:15.430626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896e942bc87a'
down_revision: Union[str, Sequence[str], None] = 'abfb62d1e907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('top_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'top_up')
    # ### end Alembic commands ###
